@baseUrl = http://localhost:8080
@authToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzM2MDM5OSwiZXhwIjoxNzY3NDQ2Nzk5fQ.PcHoIKo1oA2YkRQBQjo_QNiS92PINntTsaUYwzXtK9bcPmEECFaqD9SkPpPKbhT5

### 2.1 Логин (получение токена)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

### PersonController ###

# Создать человека
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "John Doe2",
  "age": 32
}

###

# Получить человека по ID
GET http://localhost:8080/api/persons/1
###

# Получить всех людей
GET http://localhost:8080/api/persons
###

# Обновить человека по ID
PUT http://localhost:8080/api/persons/4
Content-Type: application/json

{
  "name": "Jane Doe",
  "age": 31
}

###

# Удалить человека
DELETE http://localhost:8080/api/persons/1
###

### SaleController ###

# Создать продажу
POST http://localhost:8080/api/sales
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "product": "LaptopT",
  "amount": 1200.11
}

###

# Получить все продажи
GET http://localhost:8080/api/sales
Authorization: Bearer {{authToken}}
###

### AiResultController ###

# Создать AI результат
POST http://localhost:8080/api/ai
Content-Type: application/json

{
  "inputData": "Hello AI",
  "outputData": "Hello Human"
}

###

# Получить все AI результаты
GET http://localhost:8080/api/ai
